// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/path (interfaces: Scope)

// Package path is a generated GoMock package.
package path

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockScope is a mock of Scope interface
type MockScope struct {
	ctrl     *gomock.Controller
	recorder *MockScopeMockRecorder
}

// MockScopeMockRecorder is the mock recorder for MockScope
type MockScopeMockRecorder struct {
	mock *MockScope
}

// NewMockScope creates a new mock instance
func NewMockScope(ctrl *gomock.Controller) *MockScope {
	mock := &MockScope{ctrl: ctrl}
	mock.recorder = &MockScopeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScope) EXPECT() *MockScopeMockRecorder {
	return m.recorder
}

// GetAllIdents mocks base method
func (m *MockScope) GetAllIdents() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIdents")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllIdents indicates an expected call of GetAllIdents
func (mr *MockScopeMockRecorder) GetAllIdents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIdents", reflect.TypeOf((*MockScope)(nil).GetAllIdents))
}

// GetIdentValue mocks base method
func (m *MockScope) GetIdentValue(arg0 string) (Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentValue", arg0)
	ret0, _ := ret[0].(Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentValue indicates an expected call of GetIdentValue
func (mr *MockScopeMockRecorder) GetIdentValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentValue", reflect.TypeOf((*MockScope)(nil).GetIdentValue), arg0)
}

// RunOperation mocks base method
func (m *MockScope) RunOperation(arg0 Operation, arg1 Scope) (Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunOperation", arg0, arg1)
	ret0, _ := ret[0].(Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunOperation indicates an expected call of RunOperation
func (mr *MockScopeMockRecorder) RunOperation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunOperation", reflect.TypeOf((*MockScope)(nil).RunOperation), arg0, arg1)
}
